$(document).ready(function(){let firstNamePassager=$('.coord-firstName').val();let lastNamePassager=$('.coord-lastName').val();$(`.booking-passager-roomList0-adult0-civility option[value="${$('input[name=civility]:checked').val()}"]`).attr('selected','selected');$('.booking-passager-roomList0-adult0-firstName').val(firstNamePassager);$('.booking-passager-roomList0-adult0-lastName').val(lastNamePassager);});$(".booking-customer-civility").change(function(){if($('input:radio[id="principal"]').is(':checked')){$(".booking-passager-roomList0-adult0-civility").val($(this).val()).change();}});$('.coord-firstName').keyup(function(e){if(!$('input:radio[id="principal"]').is(':checked')){$('.booking-passager-roomList0-adult0-firstName').val(null);}
if($('input:radio[id="principal"]').is(':checked')){let firstNamePassager=$('.coord-firstName').val();$('.booking-passager-roomList0-adult0-firstName').val(firstNamePassager);}});$('.coord-lastName').keyup(function(e){if(!$('input:radio[id="principal"]').is(':checked')){$('.booking-passager-roomList0-adult0-lastName').val(null);}
if($('input:radio[id="principal"]').is(':checked')){let lastNamePassager=$('.coord-lastName').val();$('.booking-passager-roomList0-adult0-lastName').val(lastNamePassager);}});$(".principal").change(function(){if($(this).val()=="1"){let firstNamePassager=$('.coord-firstName').val();$('.booking-passager-roomList0-adult0-firstName').val(firstNamePassager);let lastNamePassager=$('.coord-lastName').val();$('.booking-passager-roomList0-adult0-lastName').val(lastNamePassager);$(".booking-passager-roomList0-adult0-civility").val($('input[name=civility]:checked').val()).change();}
if($(this).val()=="2"){$('.booking-passager-roomList0-adult0-firstName').val(null);$('.booking-passager-roomList0-adult0-lastName').val(null);$('.booking-passager-roomList0-adult0-civility').val(null).change();}});$(".form__searchEngine").submit(function(){$("#loading-wrapper").show();});$(window).on('load',function(){$("#loading-wrapper").fadeOut("slow");});function split(val){return val.split(/,\s*/);}
function extractLast(term){return split(term).pop();}
$(document).on("keyup",".ville",function(){console.log("ville --- global");var idH=$(this).attr('id');if(idH=="villeD"){$("#villeR_data").html("");icon="<i class='fas fa-plane-arrival'></i>";}else{$("#villeD_data").html("")
icon="<i class='fas fa-plane-departure'></i>";}
if($(this).val().length>=3){$.getJSON("getAirport",{term:extractLast($(this).val())},function(data){let dropDown="<ul class='city-list'>";$.each(data,function(key,val){id=val.AirportCode;name=val.CityName+" ( "+val.AirportCode+" - "+val.AirportName+" ) ";name2="<strong>"+val.CityName+"</strong>"+"<br>"+val.AirportCode+" - "+val.AirportName;dropDown+="<li class='city-item' data-id='"+idH+"' data-name='"+name+"' data-val='"+id+"'>"+icon+" "+name2+"</li>";})
dropDown+="</ul>";$("#"+idH+"_data").html(dropDown)});}});$(document).on('click','.city-item',function(){console.log(".city-item --- global");data=$(this).data('val');id=$(this).data('id');name=$(this).data('name');$("#"+id).val(name);$("#"+id+"ID").val(data);$("#"+id+"_data").html("")});$(window).click(function(){$(".city-list").hide();})
$(document).ready(function(){$(".destinationCityInputApi").keyup(_.debounce(function(){const value=$(this).val();if(typeof value!=="string"||value.length<3)
return;var idH=$(this).attr('id');$("#"+idH+"_data").html("")
const settings={"async":true,"crossDomain":true,"url":"cities?value="+value,"method":"GET",};$.ajax(settings).done(function(response){let dropDown="<ul class='city-list'>";$.each(response.features,function(key,val){id=val.center[1]+","+val.center[0];nameSplit=val.place_name.split(",");console.log(nameSplit);if(nameSplit[2]==" Sahara occidental"){name=val.place_name.replace(val.place_name.split(',')[2],' Maroc');}else{name=val.place_name;}
icon="<i class='fas fa-map-marker-alt'></i>";dropDown+="<li class='city-item' data-id='"+idH+"' data-name='"+name+"' data-val='"+id+"'>"+icon+" "+name+"</li>";});$.each(response.hotels,function(key,val){id=val.id+","+val.cityId+","+val.countryId;name=val.name+" - ("+val.countryName+" , "+val.cityName+")";name2=val.name+" <strong class='ml-2'> "+" - ("+val.countryName+" , "+val.cityName+") </strong> ";icon="<i class='mdi mdi-map-marker-radius'></i>";dropDown+="<li class='city-item' data-id='"+idH+"' data-name='"+name+"' data-val='"+id+"'><i class='fa fa-building' aria-hidden='true'></i>"+icon+" "+name2+"</li>";})
dropDown+="</ul>";$("#"+idH+"_data").html(dropDown)});},400));})
$(document).ready(function(){$("#toggle-social").click(function(){if($(".mob-item").hasClass("d-none")){$(".mob-item").addClass("d-block").removeClass("d-none");$(this).find('i').removeClass("fa-chevron-up").addClass("fa-times");Cookies.set('show-social',1);}else{$(".mob-item").addClass("d-none").removeClass("d-block");$(this).find('i').addClass("fa-chevron-up").removeClass("fa-times");Cookies.set('show-social',0);}});});if(Cookies.get('show-social')!=undefined&&Cookies.get('show-social')==0){$(".mob-item").addClass("d-none").removeClass("d-block");$("#toggle-social").find('i').removeClass("fa-times").addClass("fa-chevron-up");}
$(document).ready(function(){$('.tel_phone_code-select').on('change',function(){var telcountry=$(this).children('option:selected').data('telcountry');$('#tel_country').val(telcountry);});});$(document).ready(function(){$('.element-date-select').on('change',function(){var id=$(this).data('id');var date=$('#year-'+id).val()+'-'+$('#month-'+id).val()+'-'+$('#day-'+id).val();$('#'+id).val(date);});});$(document).ready(function(){$(".open-call").on("click",function(e){e.preventDefault();$(".content").removeClass("d-md-block d-none").addClass('d-md-none d-block');let title=$('.title');$("#wrap").slideToggle("slow",function(){});});});let lineContainer=document.querySelector(".line-container");let navContainer=document.querySelector(".nav-container");lineContainer.addEventListener("click",()=>{lineContainer.classList.toggle("active");navContainer.classList.toggle("active")});$(document).on('click','.clickedInput1',function(){travelId=$(this).data('id');console.log('dataaa',travelId);event.stopPropagation();$("#Flight-passenger"+travelId).toggleClass("d-none")})
$(document).on('click','.clicked1',function(){event.stopPropagation();})
$(document).on('click','.clicked2',function(){event.stopPropagation();})
$(document).on('click','.clickedInput2',function(){travelId=$(this).data('id');console.log('dataaa',travelId);event.stopPropagation();$("#Flight-passenger2"+travelId).toggleClass("d-none")})
$("#Hotel-passenger").click(function(event){passenger();initEvent();event.stopPropagation();});$(".acceptation").change(function(){if($(this).is(':checked')){$(".resa").prop("disabled",false);}else{$(".resa").prop("disabled",true);}});$(document).ready(function(){$('.custom_select__1').each(function(){var $this=$(this),numberOfOptions=$(this).children('option').length;$this.addClass('s-hidden');$this.wrap('<div class="select"></div>');$this.after('<div class="styledSelect"></div>');var $styledSelect=$this.next('div.styledSelect');$styledSelect.text($this.children('option:selected').text());var $list=$('<ul />',{'class':'options'}).insertAfter($styledSelect);for(var i=0;i<numberOfOptions;i++){$('<li />',{text:$this.children('option').eq(i).text(),rel:$this.children('option').eq(i).val(),class:$this.children('option').eq(i).is(':selected')?'selected':''}).appendTo($list);}
var $listItems=$list.children('li');$styledSelect.click(function(e){e.stopPropagation();$('div.styledSelect.active').each(function(){$(this).removeClass('active').next('ul.options').hide();});$(this).toggleClass('active').next('ul.options').toggle();});$listItems.click(function(e){e.stopPropagation();if($this.children('option:selected').val()!=$(this).attr('rel')){$styledSelect.text($(this).text()).removeClass('active');$(this).parent().children().removeClass('selected');$(this).addClass('selected');$this.val($(this).attr('rel'));$this.val($(this).attr('rel')).trigger('change');}
$list.hide();});$(document).click(function(){$styledSelect.removeClass('active');$list.hide();});});});$('.form__searchEngine').submit(function(){let submitbutton=$(this).data("submitbutton");$("#"+submitbutton).children('#spinner').css("display","inline-block");$("#"+submitbutton).addClass("disabled");$("#"+submitbutton).prop('disabled',true).css("cursor","default");return true;});$(document).on('click','.paymentMethode',function(){id=$(this).data("id");$('.paymentType_desc').css('display','none');if($('#paymentType_desc-'+id).length){$('#paymentType_desc-'+id).css('display','block');}})
$(document).on('change','.payment_percentage',function(){let id=$(this).attr('id');$('.payment_percentage_desc').css('display','none');if($('#payment_percentage_desc-'+id).length){$('#payment_percentage_desc-'+id).css('display','block');}});flight_passenger();$(".fl-passenger").click(function(){flight_passenger();});function flight_passenger(){nbAdult=$("#flightAdult").val();nbChild=$("#flightChild").val();nbBaby=$("#flightBaby").val();txt="";if(nbAdult==1)
txt+=nbAdult+" Adulte";else if(nbAdult>1)
txt+=nbAdult+" Adultes";if(nbChild==1)
txt+=", "+nbChild+" Enfant ";else if(nbChild>1)
txt+=", "+nbChild+" Enfants ";if(nbBaby==1)
txt+=", "+nbBaby+" Bébé ";else if(nbBaby>1)
txt+=", "+nbBaby+" Bébés ";$("#Flight-passenger-input .flight-passengers-text").html(txt);}
$(".rooms").change(function(){let travelId=$(this).data('id');let typeRoom=$('#room'+travelId).val();console.log('typeRoom',typeRoom);let txt="";switch(typeRoom){case '1':txt="Individuelle";break;case '3':txt="Triple";break;case '4':txt="Quadruple";break;default:txt="Double";}
$("#adult"+travelId).val(typeRoom);$("#Flight-passenger-input"+travelId).find(".passengers-text").html(txt)
passengerPackage(typeRoom,travelId);});function passengerPackage(typeRoom,travelId){nb=typeRoom;txt="";if(nb>1){txt+=nb+" Adultes";}else{txt+=nb+" Adulte";}
$("#Flight-passenger-input2"+travelId).find(".passengers-text").html(txt);}
$(document).on('focus','.datepicker',function(){$(this).daterangepicker({"singleDatePicker":true,"showDropdowns":true,"autoApply":true,"opens":"center","minDate":new Date(),"locale":{"format":"DD/MM/YYYY","customRangeLabel":"Custom","weekLabel":"W","firstDay":1},});})
$("#type-vol").change(function(){$("#date-as-content").toggleClass("d-none");$("#date-ar-content").toggleClass("d-none");});$("#edit-search").click(function(){$("#search").toggleClass("d-none");$("#search-result").toggleClass("d-none");});$(function(){$('[role=dialog]').on('show.bs.modal',function(e){$(this).find('[role=document]').removeClass().addClass('modal-dialog '+$(e.relatedTarget).data('ui-class'))})});$(".hl-room").click(function(){$operator=$(this).val();$max_room=$("#room").attr('max');$nb=$("#room").val();if($operator=="+"&&$nb-1<$max_room&&!$(`#room-${parseInt($nb)-1}`).length){$room=``;$room+=`
        <div id="room-${parseInt($nb)-1}">
            <hr/>
            <div class="row mb-1">
                <div class="col-6">
                    <span class="text-dark">Adultes</span><br>
                </div>
                <div class="col-6">
                    <div class="number-input">
                        <button class="fl-passenger" type="button" onclick="this.parentNode.querySelector('input[type=number]').stepDown()"></button>
                        <input class="quantity" min="1" name="room[${parseInt($nb)-1}][adults]" id="adult-${parseInt($nb)-1}" value="2" max="10" type="number" readonly required>
                        <button class="fl-passenger plus" type="button" onclick="this.parentNode.querySelector('input[type=number]').stepUp()"></button>
                    </div>
                </div>
            </div>
            <div class="row mb-1">
                <div class="col-6">
                    <span class="text-dark">Enfants</span><br>
                </div>
                <div class="col-6">
                    <div class="number-input">
                        <button class="infant-age" data-id="${parseInt($nb)-1}"
                                type="button" onclick="this.parentNode.querySelector('input[type=number]').stepDown()"></button>
                        <input class="quantity" min="0" id="infant-${parseInt($nb)-1}" name="room[${parseInt($nb)-1}][children]" value="0" max="4" type="number" readonly>
                        <button class="infant-age plus" data-id="${parseInt($nb)-1}"
                                type="button" onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
                        ></button>
                    </div>
                </div>
            </div>
            <div id="infant-age-${parseInt($nb)-1}">
            </div>
        </div>`;$("#room-list").append($room)}else if($operator=="-"&&$(`#room-${parseInt($nb)}`).length){$(`#room-${$nb}`).remove();}
passenger();initEvent();});$("#Hotel-passenger-input").click(function(event){event.stopPropagation();$("#Hotel-passenger").toggleClass("d-none")});$(document).on('click','.hl-passenger',function(){passenger();});initEvent();function initEvent(){$('.infant-age').click(function(){id=$(this).data('id');nb=$("#infant-"+id).val();infant=``;if(nb>0){infant+=`<span class="hotelsearch_children_title">Âge des enfants à la fin du séjour (obligatoire)</span>`;infant+=`<div class="row mb-0">`;for($i=0;$i<nb;$i++){infant+=`
                <div class="col-6">
                    <div class="number-input-content">
                        <select class="quantity childrenAge-select" name="room[${id}][childrenAges][${$i}]" id="age${$i}" required>
                            <option value="0"> 0 an </option>
                            <option value="1" selected> 1 an </option>
                            <option value="2"> 2 ans </option>
                            <option value="3"> 3 ans </option>
                            <option value="4"> 4 ans </option>
                            <option value="5"> 5 ans </option>
                            <option value="6"> 6 ans </option>
                            <option value="7"> 7 ans </option>
                            <option value="8"> 8 ans </option>
                            <option value="9"> 9 ans </option>
                            <option value="10"> 10 ans </option>
                            <option value="11"> 11 ans </option>
                            <option value="12"> 12 ans </option>
                            <option value="13"> 13 ans </option>
                            <option value="14"> 14 ans </option>
                            <option value="15"> 15 ans </option>
                            <option value="16"> 16 ans </option>
                            <option value="17"> 17 ans </option>
                        </select>
                    </div>
                </div>`;}
infant+=`</div>`;}
$("#infant-age-"+id).html(infant);passenger();});}
passenger();function passenger(){nb=$("#room").val();nbAdult=0;nbInfant=0;for($i=0;$i<nb;$i++){nbAdult+=parseInt($("#adult-"+$i).val());nbInfant+=parseInt($("#infant-"+$i).val());}
txt="";if(nb>1){txt+=nb+" Chambres, ";}else{txt+=nb+" Chambre, ";}
if(nbAdult>1){txt+=nbAdult+" Adultes";}else{txt+=nbAdult+" Adulte";}
if(nbInfant==1)
txt+=", "+nbInfant+" Enfant ";else if(nbInfant>1)
txt+=", "+nbInfant+" Enfants ";$("#Hotel-passenger-input .passengers-text").html(txt);}
$(".account").click(function(){$("#sign-in").toggleClass("d-none");$("#sign-up").toggleClass("d-none");})
$(document).on('click','.city-item',function(){data=$(this).data('val');id=$(this).data('id');name=$(this).data('name');$("#"+id).val(name);$("#"+id+"ID").val(data);$("#"+id+"_data").html("")});$(window).click(function(){$(".city-list").hide();if(!$("#Flight-passenger").hasClass('.d-none'))
$("#Flight-passenger").addClass("d-none");if(!$("#Hotel-passenger").hasClass('.d-none'))
$("#Hotel-passenger").addClass("d-none");if(!$(".clicked1").hasClass('.d-none'))
$(".clicked1").addClass("d-none");if(!$(".clicked2").hasClass('.d-none'))
$(".clicked2").addClass("d-none");});$("#Flight-passenger-input").click(function(event){event.stopPropagation();$("#Flight-passenger").toggleClass("d-none")});$("#Flight-passenger").click(function(event){event.stopPropagation();});$('.count').addClass('disabled');$("#activity-passenger-input").find(".passengers-text").html($('#countSingle').val()+" Adultes");$("#Flight-passenger-input").find(".passengers-text").html($('#countSingle').val()+" Adultes");function plusSingle(){$('#countSingle').val(parseInt($('#countSingle').val())+1);var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function minusSingle(){if(parseInt($('#countSingle').val())!=1){$('#countSingle').val(parseInt($('#countSingle').val())-1);}else{$('#countSingle').val(1);}
var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function plusInfant(){$('#countBaby').val(parseInt($('#countBaby').val())+1);var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants ":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function minusInfant(){if(!parseInt($('#countBaby').val())==0){$('#countBaby').val(parseInt($('#countBaby').val())-1);}else{$('#countBaby').val(0);}
var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function plusChild(){$('#countChild').val(parseInt($('#countChild').val())+1);var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function minusChild(){if(!parseInt($('#countChild').val())==0){$('#countChild').val(parseInt($('#countChild').val())-1);}else{$('#countChild').val(0);}
var textActivity=$('#countSingle').val()+" Adultes";parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants ":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);$("#Flight-passenger-input").find(".passengers-text").html(textActivity);}
function plusMinor(){var textActivity=$('#countSingle').val()+" Adultes";$('#countMinor').val(parseInt($('#countMinor').val())+1);parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants ":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);}
function minusMinor(){var textActivity=$('#countSingle').val()+" Adultes";if(!parseInt($('#countMinor').val())==0){$('#countMinor').val(parseInt($('#countMinor').val())-1);}else{$('#countMinor').val(0);}
parseInt($('#countChild').val())>0?textActivity+=', '+$('#countChild').val()+" Enfants ":'';parseInt($('#countBaby').val())>0?textActivity+=', '+$('#countBaby').val()+" Bébé":'';parseInt($('#countMinor').val())>0?textActivity+=', '+$('#countMinor').val()+" Mineur":'';$("#activity-passenger-input").find(".passengers-text").html(textActivity);}
$("#activity-passenger").click(function(event){event.stopPropagation();});$("#activity-passenger-input").click(function(event){event.stopPropagation();$("#activity-passenger").toggleClass("d-none")});$(document).click((event)=>{if(!$(event.target).closest('.sw-passengers').length){$("#activity-passenger").addClass("d-none")}});$(document).on("click",".removeCity",function(){let row=$(".row-destinations").length-1
$("#destinations-"+row).remove();});$('.trasnfer-autocomplete-route').focus(function()
{index=$(this).data('index');type=$(this).data('type');$('#inputDestinationIndex').val(index);$('#inputDestinationType').val(type);$("input[name=locationType][value=ATLAS]").prop("checked",true);$("#departure_hotel_section").show();$("#departure_terminal_section").hide();$("#countryForHotelLocation").val($("#countryForHotelLocation option:first").val()).change();$("#countryForTerminalLocation").val($("#countryForTerminalLocation option:first").val()).change();$("#destinationForHotelLocation").val($("#destinationForHotelLocation option:first").val()).change();$("#hotelForHotelLocation").val($("#hotelForHotelLocation option:first").val()).change();$("#destinationForTerminalLocation").val($("#destinationForTerminalLocation option:first").val()).change();$('#destinationForHotelLocation').prop("disabled",true);$('#hotelForHotelLocation').prop("disabled",true);$('#destinationForTerminalLocation').prop("disabled",true);$("#transferDepartureSubmit").attr('disabled','disabled');$('#transferModalLocation').modal({show:true});});$('.locationTypeRadio').change(function()
{value=$(this).val();if(value=="ATLAS"){$("#departure_hotel_section").show();$("#departure_terminal_section").hide();$('#countryForHotelLocation').attr("required",true);}else{$("#departure_hotel_section").hide();$("#departure_terminal_section").show();$('#countryForHotelLocation').attr("required",false);}});$('#countryForHotelLocation').change(function()
{countryCodes=$(this).val();$('#hotelForHotelLocation').find('option').not(':first').remove();$("#transferDepartureSubmit").attr('disabled','disabled');if(countryCodes)
{$.getJSON("getDestinations",{countryCodes:countryCodes},function(data){if(data.length>0){$('#destinationForHotelLocation').find('option').not(':first').remove();data.forEach((item,idx,arr)=>{$('#destinationForHotelLocation').append($('<option>',{value:item.code,text:item.name}));});$('#destinationForHotelLocation').prop("disabled",false);$('#hotelForHotelLocation').prop("disabled",true);}});}else{$('#destinationForHotelLocation').prop("disabled",true);$('#hotelForHotelLocation').prop("disabled",true);}});$('#destinationForHotelLocation').change(function()
{countryCodes=$("#countryForHotelLocation").val();destinationCodes=$(this).val();if(destinationCodes)
{$.getJSON("getHotels",{countryCodes:countryCodes,destinationCodes:destinationCodes},function(data){console.log("Hotels : ");console.log(data);if(data.length>0){$('#hotelForHotelLocation').find('option').not(':first').remove();data.forEach((item,idx,arr)=>{$('#hotelForHotelLocation').append($('<option>',{value:item.code,text:item.name}));});$('#hotelForHotelLocation').prop("disabled",false);}});}else{$('#hotelForHotelLocation').prop("disabled",true);}});$('#hotelForHotelLocation').change(function()
{$("#transferDepartureSubmit").removeAttr('disabled');});$('#destinationForTerminalLocation').change(function()
{$("#transferDepartureSubmit").removeAttr('disabled');});$('#transferDepartureSubmit').click(function(e)
{e.preventDefault();locationType=$("input[name=locationType]:checked").val();inputDestinationIndex=$('#inputDestinationIndex').val();inputDestinationType=$('#inputDestinationType').val();if(inputDestinationType=="departure"){$('#routes-0-fromType').val(locationType);if(locationType=="ATLAS"){$(`#routes-${inputDestinationIndex}-departureName`).val($('#hotelForHotelLocation option:selected').text());$(`#routes-${inputDestinationIndex}-departureDestination`).val($('#destinationForHotelLocation option:selected').text());$(`#routes-${inputDestinationIndex}-fromCode`).val($('#hotelForHotelLocation').val());}else if(locationType=="IATA"){$(`#routes-${inputDestinationIndex}-departureName`).val($('#destinationForTerminalLocation option:selected').text());$(`#routes-${inputDestinationIndex}-departureDestination`).val($('#destinationForTerminalLocation option:selected').text());$(`#routes-${inputDestinationIndex}-fromCode`).val($('#destinationForTerminalLocation').val());}}else if(inputDestinationType=="arrival"){$('#routes-0-toType').val(locationType);if(locationType=="ATLAS"){$(`#routes-${inputDestinationIndex}-arrivalName`).val($('#hotelForHotelLocation option:selected').text());$(`#routes-${inputDestinationIndex}-arrivalDestination`).val($('#destinationForHotelLocation option:selected').text());$(`#routes-${inputDestinationIndex}-toCode`).val($('#hotelForHotelLocation').val());}else if(locationType=="IATA"){$(`#routes-${inputDestinationIndex}-arrivalName`).val($('#destinationForTerminalLocation option:selected').text());$(`#routes-${inputDestinationIndex}-arrivalDestination`).val($('#destinationForTerminalLocation option:selected').text());$(`#routes-${inputDestinationIndex}-toCode`).val($('#destinationForTerminalLocation').val());}}
modalID=$(this).data('modal');console.log(modalID);$('#'+modalID).modal('hide');});$('#countryForTerminalLocation').change(function()
{countryCodes=$(this).val();if(countryCodes)
{$.getJSON("getTerminals",{countryCodes:countryCodes},function(data){if(data.length>0){$('#destinationForTerminalLocation').find('option').not(':first').remove();data.forEach((item,idx,arr)=>{$('#destinationForTerminalLocation').append($('<option>',{value:item.code,text:item.content.description}));});$('#destinationForTerminalLocation').prop("disabled",false);}});}else{$('#destinationForTerminalLocation').prop("disabled",true);$("#transferDepartureSubmit").attr('disabled','disabled');}});